# Generated by Django 6.0.7 on 2026-09-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='submitted_by_treasurer',
            field=models.BooleanField(default=False),
        ),
    ]
