# Generated by Django 6.0.7 on 2026-09-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_contact_person_group_default_loan_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
