# Generated by Django 6.0.7 on 2026-09-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_archived_at_group_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='max_loan_percentage',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
        ),
    ]
