# Generated by Django 6.0.7 on 2026-09-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='submitted_by_treasurer',
            field=models.BooleanField(default=False),
        ),
    ]
