# Generated by Django 6.0.7 on 2026-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('contribution', 'Contribution'), ('loan_disbursement', 'Loan Request'), ('loan_repayment', 'Loan Repayment')], max_length=20),
        ),
    ]
